# vim:set ft=dockerfile:

# LOCAL DEVELOPMENT Dockerfile Test uWSGI

FROM python:2-alpine

LABEL maintainer="Paolo Casciello <paolo.casciello@scalebox.it>"

RUN mkdir -vp /var/wsgi

COPY ./requirements.txt /var/wsgi/

RUN mkdir -vp /var/wsgi-commands

COPY ./start.sh /var/wsgi-commands

WORKDIR /var/wsgi

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["/var/wsgi-commands/start.sh"]
